### ISSUE TITLE
Descontinuação do anaconda 

### ISSUE THREAD

**Issue by Douglasastro** [danielrd6/ifscube#19]
Olá Dr Daniel, faço uso do IFSCube para ajuste de espectro de galáxias, recentimente formatei meu computador e reinstalei os aplicativos que uso, porém o astroconda foi descontinuado e o IFSCube usa algumas bibliotecas do astroconda, o (STScI) não da mais suporte e agora eles estão usando o stenv que tem muitas bibliotecas parecidas com o astroconda, da para usar as bibliotecas do STENV no lugar do astroconda e continuar usando o anaconda para como ambiente para o IFSCube?

**Comment by danielrd6** [comment]
Olá, @Douglasastro . Não cheguei a testar este ambiente especificamente, mas a princípio não deves ter problemas por usar o STENV. Contudo, minha recomendação sempre é criar um ambiente especificamente para o ifscube, por que eventualmente algum pacote pode ser atualizado e fazer com que o programa pare de funcionar.

**Comment by Douglasastro** [comment]
![erro](https://github.com/danielrd6/ifscube/assets/148808114/6feeb53c-4124-43f7-89e3-6038f249ba98)

Olá Daniel fiz o que tu orientou, mas aparece essa mensagem de erro, tu sabes o por que deste erro? grato desde já!

**Comment by danielrd6** [comment]
Olá, Douglas. Sim, este erro aparece por causa de uma incompatibilidade com versões do numpy posteriores a 1.22. Tenta instalar o numpy 1.22 (ou até o 1.21) em um novo ambiente, e reinstalar o IFSCube.

Também te pediria para colar o erro em forma de texto aqui, ao invés de imagem, para que a ferramenta de busca consiga localizar, caso alguém mais se depare com ele.

**Comment by danielrd6** [comment]
Olá, Douglas. Hoje fiz as atualizações necessárias para tornar o IFSCube compatível com o Numpy 1.26, o que deve eliminar o erro que estavas experimentando.

**Comment by Douglasastro** [comment]
Olá Daniel, fiz ajuste  com o Ifscube usando a biblioteca numpy 1.21.8 e
deu certo, realmente era um problema de compatibilidade com a versão do
numpy que eu usava, eu fazia uso da versão 1.28,  aí dava um problema ao
operar array, muito obrigado pela ajuda! 😊🙂

Em ter., 14 de nov. de 2023 15:21, Daniel Ruschel Dutra <
***@***.***> escreveu:
