### ISSUE TITLE
Problems to use cube_ppxf.py example

### ISSUE THREAD

**Issue by boagoston** [danielrd6/ifscube#5]
Bom dia, Daniel. Estou com um problema com o exemplo cube_ppxf.py quando tento executa-lo, aparece essa mensagem de erro, você teria algum norte pra solucionar o problema?

(estou mandando a mensagem em portugues pois se não me engano , disseram que tu é brasileiro) 

Desde já agradeço

![Screenshot from 2020-08-31 09-21-20](https://user-images.githubusercontent.com/15131808/91720059-cd34b400-eb6c-11ea-92d7-3fca1bfc1368.png)

**Comment by danielrd6** [comment]
Olá, Bruno.

O teu erro está acontecendo por que este arquivo de exemplo está desatualizado. Eu movi todas as funções referentes ao pPXF para o script `ppxf_wrapper`. Vou tentar atualizar esse script de exemplo nessa semana, mas até lá tu já podes ir conferindo as funções do `ppxf_wrapper`.
